version: "3"
services:
  apollo-server:
    build:
      dockerfile: Dockerfile.dev
      context: ./
    ports:
      - "3000:3000"
      - "9400:9400"
    tty: true
    networks:
      - apollo-network
    volumes:
      - /app/node_modules
      - ./:/app
networks:
  apollo-network:
    external: false